services:
  app:
    build: .
    container_name: winton-corner-bot-dev
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
